# connection string : postgresql://username:password@localhost:port/db_name
# postgresql://sadiq:sadiq@localhost:5432/phone
services:
  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: phone
      POSTGRES_USER: sadiq
      POSTGRES_PASSWORD: sadiq
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d phone -U sadiq"]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - ./data/db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
